/**
 * @file objects.c
 * @brief Implementation for creation and freeing MyGit objects.
 * 
 * This file contains the creation, adding, and freeing function for mygit objects. There are three
 * primary objects: blobs, trees, and commits. Each object will be described in further detail just 
 * above where the related functions are detailed here. As a high level overview, each object is roughly
 * as follows (See objects.h for more details about each object type):
 *      Blobs: Contains the size and content of a single file.
 *      Trees: Contains the files and subdirectories of a file.
 *      Commit: Contains metadata about commits when they are made.
 * 
 * Each of these objects are stored in the "mygit/objects" directory and are referenced by their unique hash 
 * (generated by the text contents of each object). Each object is stored in a subdirectory of the objects
 * directory. The subdirectories are labeled with the first two characters of the hash and this subdirectory 
 * stores a plain-text file labeled with the object's hash (omitting the first two characters used for the 
 * directory). If there are two object hashes with the same first two characters, then that there will 
 * simply be two files in the directory titled with those characters.
 * 
 * There are three primary types of functions in this file. They are as follow:
 *      init: Creates an instance of the object and returns a string that will be put into a file.
 *      build: Uses init to get the object's string, then puts that string into a text file. The key distinction is that
 *                  unlike init, this function type handles file creation and writing.
 *      free: Frees the string created by init.
 * 
 * @author Ziyad Rahman
 * 
 */

#include "../include/objects.h"

// Blob Object Functions

/**
 * @brief Creates blob object.
 * 
 * Generates a string representation of a blob object.
 * 
 * @param file_size The size of the file in bytes.
 * @param file_text The contents of the file in a string.
 * 
 * @return A string representation of the blob object.
 * 
 */
char *init_blob(unsigned long file_size, char *file_text) {

    // char *char_file_size = malloc((file_size * 4 + 100) * sizeof(char)); // Size Buffer
    // sprintf(char_file_size, "%lu", file_size);
    size_t blob_size = strlen(file_text) + sizeof("blob") + 100; // Size Buffer

    char *blob = malloc((blob_size + 1) * sizeof(char));
    // snprintf(blob, blob_size + 1, "blob\t%s bytes \n%s", char_file_size, file_text);

    snprintf(blob, blob_size + 1,
            "%lu bits\n%s",
            file_size, file_text);

    // free(char_file_size);

    return blob;

}


/**
 * @brief Builds a blob object from a file.
 * 
 * Builds a blob object from the file. It handles getting the content 
 * for the blob and initializing it. Opening and closing the file are 
 * done through external functions. Blob object must be freed by user.
 * 
 * @param file File to be copied into a blob object.
 * 
 * @return A string representation of the blob object.
 */
char *build_blob(FILE *file) {

    char *file_text = get_file_text(file);
    unsigned long int_file_size = get_file_size(file);

    char *blob = init_blob(int_file_size, file_text);

    free(file_text);

    return blob;

}

/**
 * @brief Frees blob object.
 * 
 * Frees blob object. Used mostly for readability.
 * 
 * @param blob The blob object to be freed.
 * 
 */
void free_blob(char *blob) {

    free(blob);

}
